### ISSUE TITLE
Gibber treats whitespace-only lines as non-blank when executing block via alt-enter

### ISSUE THREAD

**Issue by mattdiamond** [gibber-cc/gibber#41]
As I understand it, `alt-enter` is supposed to execute whatever block the cursor is in, a block being defined as code surrounded by blank lines. The code editor on gibber.cc will auto-indent new lines using spaces -- which is good! -- but it seems that Gibber treats lines with space characters as non-blank. So a given block of code may appear bounded by empty lines, but pressing `alt-enter` will end up selecting more code than intended.

IMHO, the code that determines the boundaries of a block should treat whitespace-only lines as being blank. Thoughts?

**Comment by charlieroberts** [comment]
Hi Matt,

I mostly agree with this, however, I often deliberately introduce "blank" lines with whitespace in them in tutorials so that chunks of code can be selected via alt-enter but still have "blank" lines for formatting purposes. I'm not sure if I do this in gibber.cc as much as I've done it in the gibberwocky tutorials. 

I guess one alternative for me would be to change the behavior like you recommend and then have empty single-line comments replace "blank" whitespace lines. I have a feeling this would drive me crazy visually though :)

SuperCollider does this by formally declaring blocks with {} if I remember correctly. Maybe there could be one shortcut for a block defined more formally in this manner, and another for the whitespace block? The whitespace-defined block shortcut is definitely useful when live coding...

On another note, I'm enjoying looking through your repos!
