### ISSUE TITLE
Problems with tidal sequencer

### ISSUE THREAD

**Issue by ianhattwick** [gibber-cc/gibber#86]
Since there seem to be a bunch of these I thought it would make more sense to have a single log of tidal errors.

1. angle brackets with only one element throw error, stop pattern playback
`d = Drums()
d.tidal('<kd> sd ch sd')`

2. '~' in angle brackets on beat 1 are skipped (rather than creating a rest)
`d = Drums()
d.tidal('<kd ~> sd ch sd') //rest is skipped
d.tidal('kd <~ sd> ch sd') //works as expected`

3.Tidal division operator doesn't work as expected
`k= Kick()
k.trigger.tidal("[1 0 0 [0 0.5]]/2")`
Should slow the overall pattern down by 2, but instead seems to change the pattern duration correctly but doesn't shift the events to match.

**Comment by charlieroberts** [comment]
These are all fixed with a new tidal engine in a branch I have, but the annotations don't work yet. Is it worth merging into main anyways? The division operator problem in particular has bugged me forever and would be great to have working...

I'll try to tackle the annotations soon as well, but that could take an unknown amount of time.

**Comment by charlieroberts** [comment]
all fixed (!) in 85f87c56816d57c1ab6cb9f062c47a24d6ab9e79 and pushed to the main website.
